version: 2

python:
  version: "3.8"
  install: 
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true

conda:
  environment: docs/environment.yml

formats: all

sphinx:
  configuration: docs/conf.py