version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .

conda:
  environment: docs/environment.yml

formats: all

sphinx:
  configuration: docs/conf.py
