channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - numpy
  - pandoc
  - ipykernel
  - pip
  - pip:
      - nbsphinx
      - sphinx_rtd_theme
      - sphinx-copybutton
      - sphinxcontrib-bibtex